### ISSUE TITLE
Imported procedures generate spooky comment

### ISSUE THREAD

**Issue by wipe2238** [sfall-team/int2ssl#10]
<details>
    <summary>TL;DR</summary>
    
![image](https://github.com/sfall-team/int2ssl/assets/1433300/a1266a3a-2eca-4042-b240-aa9fac893c7b)

</details>

```pascal
import procedure farfunc(variable x);
procedure func1 begin call farfunc(3); end

procedure start
begin
        call func1;
end
```

...after sslc && int2ssl becomes this...

```pascal
import procedure farfunc(variable arg0);

procedure func1;
procedure start;


/*******************************************************
*    Found Procedure without body.                     *
*                                                      *
*    Name: farfunc                                     *
*                                                      *
*    Other possible name(s):                           *
*                                                      *
*******************************************************/

procedure func1
begin
    call farfunc(3);
end

procedure start
begin
    call func1();
end
```

...which looks like int2ssl is warning user about possibly defective script, and it feels kind of wrong/weird; if there are issues with using import/export, thats more of a sslc/sfall problem than decompiler. On top of that, spooky comment is generated for each use of `import` making it even spookier 😱

---

I think it would be better to keep informing about imported functions in slightly different way; it blends with code more naturally IMHO
```pascal
import procedure farfunc(variable arg0);

procedure func1;
procedure start;

procedure func1
begin
    call farfunc(3); // imported
end

procedure start
begin
    call func1();
end
```

**Comment by phobos2077** [comment]
Why do you need to inform about imported procedure? Seems stupid. int2ssl doesn't seem to fully understand the concept of imported procedures, that's why it complaints.

**Comment by NovaRain** [comment]
Now the decompiled script is:
```pas
import procedure farfunc(variable arg0);

procedure func1;
procedure start;


procedure farfunc(variable arg0) // "broken" procedure?

procedure func1
begin
   call farfunc(3);
end

procedure start
begin
   call func1();
end
```
