### ISSUE TITLE
newer Visual Studio

### ISSUE THREAD

**Issue by burner1024** [sfall-team/int2ssl#11]
Can't build for the life of me, github actions only support 2022.

**Comment by NovaRain** [comment]
Try [`windows-2019` runner image](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md), which has Visual Studio 2019.

**Comment by burner1024** [comment]
But it's still targeted to 2010, no?

**Comment by NovaRain** [comment]
Oh, I thought you already use some text tool to replace `PlatformToolset` with newer version in the project file.
