### ISSUE TITLE
Can't decompile scripts due to incorrect detection of ternary operator

### ISSUE THREAD

**Issue by phobos2077** [sfall-team/int2ssl#4]
For a list of failing scripts (mostly vanilla):
https://github.com/rotators/ReDefine.Examples/tree/master/Games/Fallout2.Steam/Errors

Code that triggers the issue:

```
procedure start begin
    critter_add_trait(self_obj, 1, 5, 8);
    if ((cur_map_index == 26) or (cur_map_index == 25)) then begin
        critter_add_trait(self_obj, 1, 6, 2);
    end
    else begin
        critter_add_trait(self_obj, 1, 6, 21);
    end
end
```

Basically this happens because of how ternary operator `x if y else z` works: it has exactly the same opcodes as IF operator, with the exception that it always has both branches (then and else) and both branches must leave 1 value in the stack (expressions).
In some old compiler `critter_add_trait` was erroneously set as a statement (no return value), while in reality (Fallout 2 v1.02d) it always returns -1. So the newer compiler will add `O_POP` after every call (if value was not used).

Because this call is the last one in both branches, it looks like a ternary operator from decompiler point of view. It seems to be impossible to distinguish between them.

If you disable the support of ternary operator altogether (buy commenting out relevant code in `BuildTreeBranch()`), the script will decompile, but with a warning about data left in stack (which won't necessarily break the game). So we must support the same behavior, so all vanilla scripts can be decompiled without error.

One possible solution is to add a command line arg that denotes the script as vanilla-compiled or "legacy" script, and disable trying to parse all new sfall syntax.

**Comment by wipe2238** [comment]
This is awesome, only a couple files from vanilla left 🥲
MegaMod seems to be lost cause, there's a whole bunch of different kinds of errors... Oh well~

https://rotators.fodev.net/wipe/ssl/pr6/

**Comment by phobos2077** [comment]
The two remaining FO2 scripts don't show any error in log, weird. They don't produce ssl?

**Comment by wipe2238** [comment]
Technically they _do_ create .ssl, but files have 0 bytes in both cases; decompilation script treat it as error. Note that JON.int is leftover from FO1, you can find same file in FO1 errors dir (and FO2 master.dat, checked minute ago to make sure it's not repacking error).

**Comment by phobos2077** [comment]
`Error: Invalid opcode at 0x00000000`
This also happens if I enabled FO1 mode and dump files. Is there any int2ssl in existence that can decompile these scripts?

**Comment by phobos2077** [comment]
I tried to hack int2ssl to be ignore invalid opcodes but it seems these scripts are from some kind of alpha compiler, it can't even read the procedures table. So I don't think there's any point trying to decompile them. If you want to inspect these scripts, you can just use hex editor for that.
